### PR TITLE
Dockerfile: install py3-lxml

### PR DESCRIPTION
**Pull request by vrutkovs**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-babybuddy/blob/main/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
lxml installed from pip no longer links to python correctly, so a
version from Alpine repos need to be installed

## Benefits of this PR and context:
Fixed app startup

## How Has This Been Tested?
Ran the image and ensured  it no longer crashes before migrations

## Source / References:
https://github.com/babybuddy/babybuddy/issues/336

### CODE REVIEW

**Comment by cdubz** [comment]
@vrutkovs based on this [SO reference](https://stackoverflow.com/questions/5178416/libxml-install-error-using-pip) I think maybe `libxml2-dev` and/or `libxslt-dev` need to be added to the [`apk add --no-cache --virtual=build-dependencies` command](https://github.com/linuxserver/docker-babybuddy/blob/0adbd66454f0ec22fc9c6afc488f12146b1d328a/Dockerfile#L12).

**Comment by aptalca** [comment]
Lxml is a new package added to upstream app so we'll have to add the os deps to the image

**Comment by vrutkovs** [comment]
Yup, it was `libxml2-dev` missing. Added it now

**Comment by aptalca** [comment]
sorry, I'm currently overseas and didn't have time to go back and forth on this. It was much quicker to submit a new PR: #12 

Thanks for the PR, though

**Comment by cdubz** [comment]
Thanks @aptalca and @Roxedus for helping get this sorted!

**Pull request closed without merging**
